name: Release

on:
 push:
    branches:
    - main
    
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Fetch tags
        run: git fetch --tags origin
        
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Clean
        run: pnpm --filter './packages/**' clean

      - name: Build
        run: pnpm --filter './packages/**' build

      - name: Test
        run: pnpm --filter './packages/**' test

      - name: Lint
        run: pnpm --filter './packages/**' lint

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
